<?php

use App\Role;
use App\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    private $data = [
        [
            'name' => 'desamirit',
            'username' => 'desamirit',
            'email' => 'desamirit@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => '6287727757986',
            'role' => 3,
        ],
        [
            'name' => 'desarowo',
            'username' => 'desarowo',
            'email' => 'desarowo@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => '6285159861101',
            'role' => 3,
        ],
        [
            'name' => 'lpk',
            'username' => 'lpk',
            'email' => 'lpk@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => '6285159861101',
            'role' => 2,
        ],
        [
            'name' => 'irfan',
            'username' => 'irfan',
            'email' => 'irfan@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => '6285159861101',
            'role' => 1,
        ],
        [
            'name' => 'agus',
            'username' => 'agus',
            'email' => 'agus@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => '6285159861101',
            'role' => 1,
        ],
        [
            'name' => 'mustofa',
            'username' => 'mustofa',
            'email' => 'mustofa@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'ngaiso',
            'username' => 'ngaiso',
            'email' => 'ngaiso@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'suyoto',
            'username' => 'suyoto',
            'email' => 'suyoto@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'tarwan',
            'username' => 'tarwan',
            'email' => 'tarwan@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'sutrisno',
            'username' => 'sutrisno',
            'email' => 'sutrisno@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'sugiyono',
            'username' => 'sugiyono',
            'email' => 'sugiyono@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'den',
            'username' => 'den',
            'email' => 'den@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'wahid',
            'username' => 'wahid',
            'email' => 'wahid@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'lekas',
            'username' => 'lekas',
            'email' => 'lekas@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'wakidin',
            'username' => 'wakidin',
            'email' => 'wakidin@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'sunar',
            'username' => 'sunar',
            'email' => 'sunar@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'rojingun',
            'username' => 'rojingun',
            'email' => 'rojingun@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'yuli',
            'username' => 'yuli',
            'email' => 'yuli@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'ipin',
            'username' => 'ipin',
            'email' => 'ipin@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'sugi',
            'username' => 'sugi',
            'email' => 'sugi@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'soleh',
            'username' => 'soleh',
            'email' => 'soleh@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'amir',
            'username' => 'amir',
            'email' => 'amir@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'sabar',
            'username' => 'sabar',
            'email' => 'sabar@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'wagino',
            'username' => 'wagino',
            'email' => 'wagino@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'arifyanto',
            'username' => 'arifyanto',
            'email' => 'arifyanto@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'wagiatno',
            'username' => 'wagiatno',
            'email' => 'wagiatno@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'paryanto',
            'username' => 'paryanto',
            'email' => 'paryanto@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'harun',
            'username' => 'harun',
            'email' => 'harun@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'puji',
            'username' => 'puji',
            'email' => 'puji@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'riyadi',
            'username' => 'riyadi',
            'email' => 'riyadi@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'toyibmustofa',
            'username' => 'toyibmustofa',
            'email' => 'toyibmustofa@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'pardi',
            'username' => 'pardi',
            'email' => 'pardi@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'jumadi',
            'username' => 'jumadi',
            'email' => 'jumadi@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'eko',
            'username' => 'eko',
            'email' => 'eko@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'yusuf',
            'username' => 'yusuf',
            'email' => 'yusuf@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'penjol',
            'username' => 'penjol',
            'email' => 'penjol@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'pairah',
            'username' => 'pairah',
            'email' => 'pairah@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'sangid',
            'username' => 'sangid',
            'email' => 'sangid@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'suyat',
            'username' => 'suyat',
            'email' => 'suyat@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'ahmad',
            'username' => 'ahmad',
            'email' => 'ahmad@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'saipul',
            'username' => 'saipul',
            'email' => 'saipul@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'kipli',
            'username' => 'kipli',
            'email' => 'kipli@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'iwan',
            'username' => 'iwan',
            'email' => 'iwan@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'bejo',
            'username' => 'bejo',
            'email' => 'bejo@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'subur',
            'username' => 'subur',
            'email' => 'subur@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'warso',
            'username' => 'warso',
            'email' => 'warso@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'wahid2',
            'username' => 'wahid2',
            'email' => 'wahid2@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'rajim',
            'username' => 'rajim',
            'email' => 'rajim@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'hamid',
            'username' => 'hamid',
            'email' => 'hamid@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'ngayit',
            'username' => 'ngayit',
            'email' => 'ngayit@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'muji',
            'username' => 'muji',
            'email' => 'muji@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'tohirin',
            'username' => 'tohirin',
            'email' => 'tohirin@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'daryanto',
            'username' => 'daryanto',
            'email' => 'daryanto@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'manijo',
            'username' => 'manijo',
            'email' => 'manijo@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
        [
            'name' => 'marno',
            'username' => 'marno',
            'email' => 'marno@gmail.com',
            'password' => 'janganlupa',
            'nomor_hp' => null,
            'role' => 1,
        ],
    ];

    public function run()
    {
        collect($this->data)
            ->map(function (array $data) {
                $role = Role::findOrFail($data['role']);

                $user = new User(
                    [
                        'name' => $data['name'],
                        'username' => $data['username'],
                        'email' => $data['email'],
                        'password' => Hash::make($data['password']),
                        'nomor_hp' => $data['nomor_hp']
                    ]
                );
                $user->role()->associate($role);
                $user->save();
            });
    }
}
